module.exports = class Data1661156520100 {
  name = 'Data1661156520100'

  async up(db) {
    await db.query(`ALTER TABLE "uniswap_factory" ALTER COLUMN "total_volume_usd" TYPE numeric`)
    await db.query(`ALTER TABLE "uniswap_factory" ALTER COLUMN "total_volume_eth" TYPE numeric`)
    await db.query(`ALTER TABLE "uniswap_factory" ALTER COLUMN "untracked_volume_usd" TYPE numeric`)
    await db.query(`ALTER TABLE "uniswap_factory" ALTER COLUMN "total_liquidity_usd" TYPE numeric`)
    await db.query(`ALTER TABLE "uniswap_factory" ALTER COLUMN "total_liquidity_eth" TYPE numeric`)
    await db.query(`ALTER TABLE "token" ALTER COLUMN "total_supply" TYPE numeric`)
    await db.query(`ALTER TABLE "token" ALTER COLUMN "trade_volume" TYPE numeric`)
    await db.query(`ALTER TABLE "token" ALTER COLUMN "trade_volume_usd" TYPE numeric`)
    await db.query(`ALTER TABLE "token" ALTER COLUMN "untracked_volume_usd" TYPE numeric`)
    await db.query(`ALTER TABLE "token" ALTER COLUMN "total_liquidity" TYPE numeric`)
    await db.query(`ALTER TABLE "token" ALTER COLUMN "derived_eth" TYPE numeric`)
    await db.query(`ALTER TABLE "liquidity_position" ALTER COLUMN "liquidity_token_balance" TYPE numeric`)
    await db.query(`ALTER TABLE "token_swap_event" ALTER COLUMN "amount_usd" TYPE numeric`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "reserve0" TYPE numeric`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "reserve1" TYPE numeric`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "total_supply" TYPE numeric`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "reserve_eth" TYPE numeric`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "reserve_usd" TYPE numeric`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "tracked_reserve_eth" TYPE numeric`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "token0_price" TYPE numeric`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "token1_price" TYPE numeric`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "volume_token0" TYPE numeric`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "volume_token1" TYPE numeric`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "volume_usd" TYPE numeric`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "untracked_volume_usd" TYPE numeric`)
    await db.query(`ALTER TABLE "bundle" ALTER COLUMN "eth_price" TYPE numeric`)
    await db.query(`ALTER TABLE "swap_stat_period" ALTER COLUMN "total_amount_usd" TYPE numeric`)
    await db.query(`ALTER TABLE "swapper" ALTER COLUMN "day_amount_usd" TYPE numeric`)
    await db.query(`ALTER TABLE "swapper" ALTER COLUMN "week_amount_usd" TYPE numeric`)
    await db.query(`ALTER TABLE "swapper" ALTER COLUMN "month_amount_usd" TYPE numeric`)
  }

  async down(db) {
    await db.query(`ALTER TABLE "swap_stat_period" ALTER COLUMN "total_amount_usd" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "swapper" ALTER COLUMN "day_amount_usd" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "swapper" ALTER COLUMN "week_amount_usd" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "swapper" ALTER COLUMN "month_amount_usd" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "uniswap_factory" ALTER COLUMN "total_volume_usd" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "uniswap_factory" ALTER COLUMN "total_volume_eth" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "uniswap_factory" ALTER COLUMN "untracked_volume_usd" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "uniswap_factory" ALTER COLUMN "total_liquidity_usd" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "uniswap_factory" ALTER COLUMN "total_liquidity_eth" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "token" ALTER COLUMN "total_supply" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "token" ALTER COLUMN "trade_volume" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "token" ALTER COLUMN "trade_volume_usd" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "token" ALTER COLUMN "untracked_volume_usd" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "token" ALTER COLUMN "total_liquidity" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "token" ALTER COLUMN "derived_eth" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "liquidity_position" ALTER COLUMN "liquidity_token_balance" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "token_swap_event" ALTER COLUMN "amount_usd" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "reserve0" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "reserve1" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "total_supply" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "reserve_eth" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "reserve_usd" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "tracked_reserve_eth" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "token0_price" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "token1_price" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "volume_token0" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "volume_token1" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "volume_usd" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "pair" ALTER COLUMN "untracked_volume_usd" TYPE numeric(38,20)`)
    await db.query(`ALTER TABLE "bundle" ALTER COLUMN "eth_price" TYPE numeric(38,20)`)
  }
}
