module.exports = class Data1664394901793 {
  name = 'Data1664394901793'

  async up(db) {
    await db.query(`CREATE TABLE "uniswap_factory" ("id" character varying NOT NULL, "pair_count" integer NOT NULL, "total_volume_usd" numeric NOT NULL, "total_volume_eth" numeric NOT NULL, "untracked_volume_usd" numeric NOT NULL, "total_liquidity_usd" numeric NOT NULL, "total_liquidity_eth" numeric NOT NULL, "tx_count" integer NOT NULL, CONSTRAINT "PK_89dd10e302aec5fac5bbf1d35f0" PRIMARY KEY ("id"))`)
    await db.query(`CREATE TABLE "token" ("id" character varying NOT NULL, "symbol" text NOT NULL, "name" text NOT NULL, "decimals" integer NOT NULL, "total_supply" text NOT NULL, "trade_volume" numeric NOT NULL, "trade_volume_usd" numeric NOT NULL, "untracked_volume_usd" numeric NOT NULL, "tx_count" integer NOT NULL, "total_liquidity" numeric NOT NULL, "derived_eth" numeric NOT NULL, CONSTRAINT "PK_82fae97f905930df5d62a702fc9" PRIMARY KEY ("id"))`)
    await db.query(`CREATE TABLE "liquidity_position" ("id" character varying NOT NULL, "user" text NOT NULL, "liquidity_token_balance" numeric NOT NULL, "pair_id" character varying, CONSTRAINT "PK_db00d963c96b3914d26abe3c3d2" PRIMARY KEY ("id"))`)
    await db.query(`CREATE INDEX "IDX_5a626c8b8962dc01e0f8801be6" ON "liquidity_position" ("pair_id") `)
    await db.query(`CREATE TABLE "transaction" ("id" character varying NOT NULL, "block_number" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "swaps" text array, CONSTRAINT "PK_89eadb93a89810556e1cbcd6ab9" PRIMARY KEY ("id"))`)
    await db.query(`CREATE TABLE "pool" ("id" character varying NOT NULL, "num_tokens" integer NOT NULL, "tokens" text array NOT NULL, "balances" numeric array NOT NULL, "lp_token" text NOT NULL, "a" numeric NOT NULL, "swap_fee" numeric NOT NULL, "admin_fee" numeric NOT NULL, "virtual_price" numeric NOT NULL, "owner" text NOT NULL, CONSTRAINT "PK_db1bfe411e1516c01120b85f8fe" PRIMARY KEY ("id"))`)
    await db.query(`CREATE TABLE "token_swap_event" ("id" character varying NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "pair_id" character varying, "pool_id" character varying, "buyer" text NOT NULL, "sold_amount" numeric NOT NULL, "bought_amount" numeric NOT NULL, "amount_usd" numeric NOT NULL, "transaction_id" character varying, "token_sold_id" character varying, "token_bought_id" character varying, CONSTRAINT "PK_bf9b123e246631a6698c5a8ed52" PRIMARY KEY ("id"))`)
    await db.query(`CREATE INDEX "IDX_79c145ca378cfad070fde0ab33" ON "token_swap_event" ("transaction_id") `)
    await db.query(`CREATE INDEX "IDX_3446160413d94205556988ca5a" ON "token_swap_event" ("timestamp") `)
    await db.query(`CREATE INDEX "IDX_9a7be24d89e36333bbd6399011" ON "token_swap_event" ("pair_id") `)
    await db.query(`CREATE INDEX "IDX_5d68341e6a05564d283c5aa7e1" ON "token_swap_event" ("pool_id") `)
    await db.query(`CREATE INDEX "IDX_4195a16a3b81bd81e8aa610b79" ON "token_swap_event" ("buyer") `)
    await db.query(`CREATE INDEX "IDX_04fb3b7ccbc5a88b68d04ca48d" ON "token_swap_event" ("token_sold_id") `)
    await db.query(`CREATE INDEX "IDX_ec6a1e67ff2c6ae31899909de5" ON "token_swap_event" ("token_bought_id") `)
    await db.query(`CREATE TABLE "pair" ("id" character varying NOT NULL, "token0_id" character varying NOT NULL, "token1_id" character varying NOT NULL, "reserve0" numeric NOT NULL, "reserve1" numeric NOT NULL, "total_supply" numeric NOT NULL, "reserve_eth" numeric NOT NULL, "reserve_usd" numeric NOT NULL, "tracked_reserve_eth" numeric NOT NULL, "token0_price" numeric NOT NULL, "token1_price" numeric NOT NULL, "volume_token0" numeric NOT NULL, "volume_token1" numeric NOT NULL, "volume_usd" numeric NOT NULL, "untracked_volume_usd" numeric NOT NULL, "tx_count" integer NOT NULL, "created_at_timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at_block_number" integer NOT NULL, "liquidity_provider_count" integer NOT NULL, CONSTRAINT "PK_3eaf216329c5c50aedb94fa797e" PRIMARY KEY ("id"))`)
    await db.query(`CREATE INDEX "IDX_f74dc53460944a424b56b8f7da" ON "pair" ("token0_id") `)
    await db.query(`CREATE INDEX "IDX_4419691fc411b8af754dfa65ce" ON "pair" ("token1_id") `)
    await db.query(`CREATE TABLE "bundle" ("id" character varying NOT NULL, "eth_price" numeric NOT NULL, CONSTRAINT "PK_637e3f87e837d6532109c198dea" PRIMARY KEY ("id"))`)
    await db.query(`CREATE TABLE "swap_stat_period" ("id" character varying NOT NULL, "from" TIMESTAMP WITH TIME ZONE NOT NULL, "to" TIMESTAMP WITH TIME ZONE NOT NULL, "swaps_count" integer NOT NULL, "pairs_count" integer NOT NULL, "users_count" integer NOT NULL, "total_amount_usd" numeric NOT NULL, CONSTRAINT "PK_d565eb3e3cf20b3a7fe0788e5eb" PRIMARY KEY ("id"))`)
    await db.query(`CREATE TABLE "swapper" ("id" character varying NOT NULL, "type" character varying(5) NOT NULL, "day_amount_usd" numeric NOT NULL, "week_amount_usd" numeric NOT NULL, "month_amount_usd" numeric NOT NULL, CONSTRAINT "PK_f3c23c1fea67a1be178aa5091d1" PRIMARY KEY ("id"))`)
    await db.query(`ALTER TABLE "liquidity_position" ADD CONSTRAINT "FK_5a626c8b8962dc01e0f8801be61" FOREIGN KEY ("pair_id") REFERENCES "pair"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "token_swap_event" ADD CONSTRAINT "FK_79c145ca378cfad070fde0ab334" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "token_swap_event" ADD CONSTRAINT "FK_9a7be24d89e36333bbd6399011b" FOREIGN KEY ("pair_id") REFERENCES "pair"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "token_swap_event" ADD CONSTRAINT "FK_5d68341e6a05564d283c5aa7e1f" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "token_swap_event" ADD CONSTRAINT "FK_04fb3b7ccbc5a88b68d04ca48d6" FOREIGN KEY ("token_sold_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "token_swap_event" ADD CONSTRAINT "FK_ec6a1e67ff2c6ae31899909de53" FOREIGN KEY ("token_bought_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "pair" ADD CONSTRAINT "FK_f74dc53460944a424b56b8f7da5" FOREIGN KEY ("token0_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "pair" ADD CONSTRAINT "FK_4419691fc411b8af754dfa65ce4" FOREIGN KEY ("token1_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
  }

  async down(db) {
    await db.query(`DROP TABLE "uniswap_factory"`)
    await db.query(`DROP TABLE "token"`)
    await db.query(`DROP TABLE "liquidity_position"`)
    await db.query(`DROP INDEX "public"."IDX_5a626c8b8962dc01e0f8801be6"`)
    await db.query(`DROP TABLE "transaction"`)
    await db.query(`DROP TABLE "pool"`)
    await db.query(`DROP TABLE "token_swap_event"`)
    await db.query(`DROP INDEX "public"."IDX_79c145ca378cfad070fde0ab33"`)
    await db.query(`DROP INDEX "public"."IDX_3446160413d94205556988ca5a"`)
    await db.query(`DROP INDEX "public"."IDX_9a7be24d89e36333bbd6399011"`)
    await db.query(`DROP INDEX "public"."IDX_5d68341e6a05564d283c5aa7e1"`)
    await db.query(`DROP INDEX "public"."IDX_4195a16a3b81bd81e8aa610b79"`)
    await db.query(`DROP INDEX "public"."IDX_04fb3b7ccbc5a88b68d04ca48d"`)
    await db.query(`DROP INDEX "public"."IDX_ec6a1e67ff2c6ae31899909de5"`)
    await db.query(`DROP TABLE "pair"`)
    await db.query(`DROP INDEX "public"."IDX_f74dc53460944a424b56b8f7da"`)
    await db.query(`DROP INDEX "public"."IDX_4419691fc411b8af754dfa65ce"`)
    await db.query(`DROP TABLE "bundle"`)
    await db.query(`DROP TABLE "swap_stat_period"`)
    await db.query(`DROP TABLE "swapper"`)
    await db.query(`ALTER TABLE "liquidity_position" DROP CONSTRAINT "FK_5a626c8b8962dc01e0f8801be61"`)
    await db.query(`ALTER TABLE "token_swap_event" DROP CONSTRAINT "FK_79c145ca378cfad070fde0ab334"`)
    await db.query(`ALTER TABLE "token_swap_event" DROP CONSTRAINT "FK_9a7be24d89e36333bbd6399011b"`)
    await db.query(`ALTER TABLE "token_swap_event" DROP CONSTRAINT "FK_5d68341e6a05564d283c5aa7e1f"`)
    await db.query(`ALTER TABLE "token_swap_event" DROP CONSTRAINT "FK_04fb3b7ccbc5a88b68d04ca48d6"`)
    await db.query(`ALTER TABLE "token_swap_event" DROP CONSTRAINT "FK_ec6a1e67ff2c6ae31899909de53"`)
    await db.query(`ALTER TABLE "pair" DROP CONSTRAINT "FK_f74dc53460944a424b56b8f7da5"`)
    await db.query(`ALTER TABLE "pair" DROP CONSTRAINT "FK_4419691fc411b8af754dfa65ce4"`)
  }
}
